# permissions for end users to view horizontalportraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: horizontalportrait-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kapacity
    app.kubernetes.io/part-of: kapacity
    app.kubernetes.io/managed-by: kustomize
  name: horizontalportrait-viewer-role
rules:
- apiGroups:
  - autoscaling.kapacity.traas.io
  resources:
  - horizontalportraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.kapacity.traas.io
  resources:
  - horizontalportraits/status
  verbs:
  - get
