# permissions for end users to edit horizontalportraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: horizontalportrait-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kapacity
    app.kubernetes.io/part-of: kapacity
    app.kubernetes.io/managed-by: kustomize
  name: horizontalportrait-editor-role
rules:
- apiGroups:
  - autoscaling.kapacity.traas.io
  resources:
  - horizontalportraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.kapacity.traas.io
  resources:
  - horizontalportraits/status
  verbs:
  - get
