# permissions for end users to edit intelligenthorizontalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intelligenthorizontalpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers/status
  verbs:
  - get
