# permissions for end users to view intelligenthorizontalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intelligenthorizontalpodautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers/status
  verbs:
  - get
